In [ ]:
import pandas as pd
import numpy as np

import sys
from pathlib import Path
sys.path.append('..')

In [ ]:
from paths import DATA_DIR
df = pd.read_csv(DATA_DIR / "2025_june_raw.csv", encoding='cp1251')

In [3]:
df.head(3)

,Submitted at,Ваша основна зайнятість в ІТ зараз...,"ЗАРПЛАТА / СУМАРНИЙ ДОХІД в IT у $$$ за місяць, лише ставка \nЧИСТИМИ - після сплати податків",Всі бонуси (на місяць),Тайтл,Категорія,Почніть вводити і оберіть вашу ОСНОВНУ посаду зі списку,"У якій сфері проєкт, в якому ви зараз працюєте?",Вкажіть вашу основну спеціалізацію,Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?,Основна мова програмування,"Основний напрям роботи компанії, в якій працюєте",Кількість спеціалістів у вашій компанії в Україні,Загальний стаж роботи за нинішньою ІТ-спеціальністю,Знання англійської мови,Де ви зараз живете?,За яким напрямом ви навчалися / навчаєтеся у виші?,Ваш вік
0,2025-05-26 06:52:09,Втратив(-ла) роботу / звільнився(-лася) і шука...,2000.0,0.0,Middle,Marketing,Marketing Manager,"Adtech / Advertising / Marketing, Blockchain, ...",NaN,"Ні, не використовую",NaN,Продуктова,до 50,4.00,Upper-Intermediate,В Україні,Інші гуманітарні та суспільні науки,21.0
1,2025-05-26 06:52:15,Працюю в IT-компанії / ІТ-департаменті,3000.0,0.0,Senior,SE,"Software Engineer / Developer (frontend, backe...",Retail / marketplace,Full Stack розробка,NaN,1С,Продуктова,до 10 спеціалістів,8.00,Pre-Intermediate,В Україні,"Точні науки (математика, інформатика)",33.0
2,2025-05-26 06:53:32,Працюю в IT-компанії / ІТ-департаменті,282.0,0.0,Junior,SE,"Software Engineer / Developer (frontend, backe...","Edtech / Education, AI / ML, Real estate",Back-end розробка,NaN,C# / .NET,Сервісна (аутсорсингова),до 50,0.25,Pre-Intermediate,В Україні,"Природничі науки (фізика, хімія, біологія)",32.0

In [29]:
df.columns

Index(['Submitted at', 'Ваша основна зайнятість в ІТ зараз...',
       'ЗАРПЛАТА / СУМАРНИЙ ДОХІД в IT у $$$ за місяць, лише ставка \nЧИСТИМИ - після сплати податків',
       'Всі бонуси (на місяць)', 'Тайтл', 'Категорія',
       'Почніть вводити і оберіть вашу ОСНОВНУ посаду зі списку',
       'У якій сфері проєкт, в якому ви зараз працюєте?',
       'Вкажіть вашу основну спеціалізацію',
       'Чи використовуєте ви у своїй роботі мови програмування (одну чи декілька)?',
       'Основна мова програмування',
       'Основний напрям роботи компанії, в якій працюєте',
       'Кількість спеціалістів у вашій компанії в Україні',
       'Загальний стаж роботи за нинішньою ІТ-спеціальністю',
       'Знання англійської мови', 'Де ви зараз живете?',
       'За яким напрямом ви навчалися / навчаєтеся у виші?', 'Ваш вік'],
      dtype='object')

In [38]:
# Вибір ключових фіч
selected_features = {
    'ЗАРПЛАТА / СУМАРНИЙ ДОХІД в IT у $$$ за місяць, лише ставка \nЧИСТИМИ - після сплати податків': 'salary_usd',
    'Тайтл': 'title',
    'Категорія': 'category',
    'Почніть вводити і оберіть вашу ОСНОВНУ посаду зі списку': 'position',
    'Вкажіть вашу основну спеціалізацію': 'specialization',
    'Основна мова програмування': 'main_language',
    'Знання англійської мови': 'english_level',
    'Загальний стаж роботи за нинішньою ІТ-спеціальністю': 'it_experience_years',
}

# Створити копію датафрейму лише з цими фічами та перейменувати колонки
df_prepared = df[list(selected_features.keys())].copy()
df_prepared.rename(columns=selected_features, inplace=True)
df_prepared.fillna({'main_language':'Unknown'}, inplace=True)
df_prepared.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11686 entries, 0 to 11685
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   salary_usd           11685 non-null  float64
 1   title                11686 non-null  object
 2   category             11686 non-null  object
 3   position             11686 non-null  object
 4   specialization       11686 non-null  object
 5   main_language        11686 non-null  object
 6   english_level        11686 non-null  object
 7   it_experience_years  11686 non-null  float64
dtypes: float64(2), object(6)
memory usage: 730.5+ KB

In [63]:
df_prepared = df_prepared.dropna(subset=['salary_usd'])
df_prepared.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11685 entries, 0 to 11685
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   salary_usd           11685 non-null  float64
 1   title                11685 non-null  object
 2   category             11685 non-null  object
 3   position             11685 non-null  object
 4   specialization       11685 non-null  object
 5   main_language        11685 non-null  object
 6   english_level        11685 non-null  object
 7   it_experience_years  11685 non-null  float64
dtypes: float64(2), object(6)
memory usage: 821.6+ KB

In [64]:
df_prepared['title'].value_counts()

title
Middle                                   3869
Senior                                   3421
Junior                                   1472
Lead / Team Lead                          948
Manager                                   565
Немає тайтлу                              436
Tech Lead                                 290
Head                                      249
CEO / C-level (Chief) / Director / VP     152
Intern/Trainee                            107
Architect                                  96
Staff                                      42
Principal                                  38
Name: count, dtype: int64

In [67]:
# трансформація і покарщення деяких категорій
category_map = {
    'SE': 'Software Engineer',
    'QA': 'Quality Assurance',
    'DS': 'Data Scientist',
    'Product Mgmt': 'Product Management',
    'Project Mgmt': 'Project Management',
    'Other Mgmt': 'Other Management'
}

df_prepared['category'] = df_prepared['category'].replace(category_map)
df_prepared['category'].value_counts()

category
Software Engineer                     5113
Quality Assurance                     1975
Analyst                                551
DevOps                                 506
Project Management                     469
Data Scientist                         330
Product Management                     312
UI/UX, Product Design                  299
HR                                     281
Marketing                              229
Rcrt                                   210
Brand                                  169
Sales                                  134
SysAdmin                               130
Artist/Animator                        111
Other Management                       105
Tech Leadership                         91
Customer Support                        65
Design                                  64
Technical Support                       61
Security                                57
Game design                             56
LD                                      45
Support                                 44
Finance                                 35
Agile Mgmt                              34
Legal                                   33
General Leadership                      33
Office manager / Admin / Assistant      28
Other mgmt                              25
Tech Wr./Lclz                           24
Consultant                              21
Customer Success                        18
Hardware                                17
DBA                                      9
Customer support                         1
Name: count, dtype: int64

In [75]:
import re

# групування ідентичний або рідкісних позицій (для зменшення шуму)

def normalize_position(pos):
    pos = pos.lower()
    # Групування за ключовими словами
    if 'developer' in pos or 'розробник' in pos:
        return 'Developer'
    if 'qa' in pos or 'quality assurance' in pos or 'тестувальник' in pos:
        return 'QA'
    if 'analyst' in pos or 'аналітик' in pos:
        return 'Analyst'
    if 'manager' in pos or 'менеджер' in pos:
        return 'Manager'
    if 'devops' in pos:
        return 'DevOps'
    if 'designer' in pos or 'дизайнер' in pos:
        return 'Designer'
    if 'architect' in pos or 'архітектор' in pos:
        return 'Architect'
    if 'data scientist' in pos or 'data science' in pos:
        return 'Data Scientist'
    if 'support' in pos or 'підтримка' in pos:
        return 'Support'
    if 'admin' in pos or 'адміністратор' in pos:
        return 'Admin'
    return pos.strip().title()

# нормалізація позицій
df_prepared['position_grouped'] = df_prepared['position'].astype(str).apply(normalize_position)

# Рідкісні позиції (менше 50) замінимо на "Other"
counts = df_prepared['position_grouped'].value_counts()
rare_positions = counts[counts < 50].index
df_prepared['position_grouped'] = df_prepared['position_grouped'].replace(rare_positions, 'Other')

position_grouped
Developer                                                   4854
QA                                                          1951
Other                                                       1414
Manager                                                     1235
Analyst                                                      534
DevOps                                                       442
Designer                                                     371
Support                                                      146
Data Engineer / Big Data Engineer                            138
Tech Lead / Engineering Lead                                 134
Recruiter / Recruitment Specialist / Technical Recruiter     130
Admin                                                        113
Architect                                                     87
Data Scientist                                                75
Product Owner (У Продакт Менеджменті)                         61
Name: count, dtype: int64

In [76]:
df_prepared['position_grouped'].value_counts()

position_grouped
Developer                                                   4854
QA                                                          1951
Other                                                       1414
Manager                                                     1235
Analyst                                                      534
DevOps                                                       442
Designer                                                     371
Support                                                      146
Data Engineer / Big Data Engineer                            138
Tech Lead / Engineering Lead                                 134
Recruiter / Recruitment Specialist / Technical Recruiter     130
Admin                                                        113
Architect                                                     87
Data Scientist                                                75
Product Owner (У Продакт Менеджменті)                         61
Name: count, dtype: int64

In [78]:
df_prepared['specialization'].value_counts()

specialization
Unknown                                                                7029
Back-end розробка                                                      1894
Front-end розробка                                                     1104
Full stack розробка                                                     915
Mobile розробка                                                         438
Desktop                                                                 103
Embedded                                                                 88
Платформна / bi / low-code розробка (salesforce, sap, 1с тощо)           77
Database розробка                                                        16
Other                                                                     7
System programming                                                        1
Statistical programmer, обробка і аналіз даних клінічних досліджень       1
Solution developer                                                        1
Windows / linux kernel developer                                          1
Qa automation                                                             1
Report dev                                                                1
Applied programmer                                                        1
Reversing                                                                 1
Blockchain (on chain architecture and development)                        1
Технічна підтримка                                                        1
Geospatial/general                                                        1
Кросплатформна розробка                                                   1
Rpa developer & ai developer                                              1
Developer advocate                                                        1
Name: count, dtype: int64

In [81]:
# too many features with 'unknown'
df_prepared = df_prepared.drop(columns=['specialization'])
df_prepared

,salary_usd,title,category,position,main_language,english_level,it_experience_years,position_grouped
0,2000.0,Middle,Marketing,Marketing Manager,Unknown,Upper-Intermediate,4.00,Manager
1,3000.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",1С,Pre-Intermediate,8.00,Developer
2,282.0,Junior,Software Engineer,"Software Engineer / Developer (frontend, backe...",C# / .NET,Pre-Intermediate,0.25,Developer
3,2700.0,Middle,Quality Assurance,Manual QA,Python,Upper-Intermediate,4.00,QA
4,2500.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",C++,Intermediate,4.00,Developer
...,...,...,...,...,...,...,...,...
11681,3000.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Java,Intermediate,4.00,Developer
11682,2500.0,Middle,Analyst,System Analyst,Unknown,Upper-Intermediate,1.50,Analyst
11683,4500.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",TypeScript,Upper-Intermediate,9.00,Developer
11684,1000.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Java,Upper-Intermediate,3.00,Developer
11685,1900.0,Middle,Analyst,Business Analyst (BA),Unknown,Upper-Intermediate,3.00,Analyst

In [82]:
df_prepared['main_language'].value_counts()

main_language
Unknown                 3961
TypeScript              1521
Python                  1234
JavaScript               870
Java                     832
                        ...
DataWeave / MuleSoft       1
LabVIEW                    1
HTML-CSS                   1
MATLAB                     1
Rell                       1
Name: count, Length: 77, dtype: int64

In [ ]:
df_prepared = df_prepared.drop(columns=['main_language'])

In [84]:
df_prepared['english_level'].value_counts()

english_level
Upper-Intermediate    5350
Intermediate          3215
Advanced              1776
Pre-Intermediate      1071
Elementary             257
Не знаю взагалі         16
Name: count, dtype: int64

In [85]:
df_prepared.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11685 entries, 0 to 11685
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   salary_usd           11685 non-null  float64
 1   title                11685 non-null  object
 2   category             11685 non-null  object
 3   position             11685 non-null  object
 4   english_level        11685 non-null  object
 5   it_experience_years  11685 non-null  float64
 6   position_grouped     11685 non-null  object
dtypes: float64(2), object(5)
memory usage: 730.3+ KB

In [87]:
df_prepared.head(30)

,salary_usd,title,category,position,english_level,it_experience_years,position_grouped
0,2000.0,Middle,Marketing,Marketing Manager,Upper-Intermediate,4.00,Manager
1,3000.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Pre-Intermediate,8.00,Developer
2,282.0,Junior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Pre-Intermediate,0.25,Developer
3,2700.0,Middle,Quality Assurance,Manual QA,Upper-Intermediate,4.00,QA
4,2500.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Intermediate,4.00,Developer
5,2030.0,Middle,Project Management,Project Manager (PM),Upper-Intermediate,7.00,Manager
6,3200.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,3.00,Developer
7,4000.0,Senior,"UI/UX, Product Design",UI/UX Designer,Upper-Intermediate,5.00,Designer
8,1200.0,Junior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Intermediate,2.00,Developer
9,800.0,Junior,DevOps,DevOps Engineer,Pre-Intermediate,1.00,DevOps
10,1600.0,Head,Marketing,Head of Marketing,Upper-Intermediate,4.00,Other
11,2100.0,Middle,Analyst,Data Analyst,Advanced,4.00,Analyst
12,4500.0,Senior,Product Management,Product Manager,Advanced,9.00,Manager
13,2000.0,Lead / Team Lead,Quality Assurance,Manual QA,Intermediate,2.00,QA
14,3000.0,Middle,Product Management,Product Manager,Advanced,2.00,Manager
15,2430.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,0.50,Developer
16,4100.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,7.00,Developer
17,4000.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Advanced,10.00,Developer
18,1150.0,Junior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Intermediate,1.50,Developer
19,2000.0,Senior,"UI/UX, Product Design",Product Designer,Upper-Intermediate,5.00,Designer
20,3000.0,Head,Marketing,Head of Affiliates,Pre-Intermediate,13.00,Other
21,5300.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,4.00,Developer
22,400.0,Junior,Quality Assurance,Manual QA,Intermediate,0.50,QA
23,1500.0,Manager,Product Management,Product Owner (у продакт менеджменті),Upper-Intermediate,0.50,Product Owner (У Продакт Менеджменті)
24,4000.0,Head,HR,HR Director (HRD),Upper-Intermediate,9.00,Other
25,2500.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,6.00,Developer
26,700.0,Junior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,2.00,Developer
27,2100.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Intermediate,2.00,Developer
28,3300.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,5.00,Developer
29,3700.0,Middle,Quality Assurance,Manual QA,Upper-Intermediate,4.00,QA

In [97]:
df_prepared['position'].value_counts().head(50)

position
Software Engineer / Developer (frontend, backend, mobile, gamedev, embedded etc )    4842
Manual QA                                                                            1166
DevOps Engineer                                                                       425
Project Manager (PM)                                                                  393
Automation QA / AQA                                                                   370
General QA                                                                            257
Business Analyst (BA)                                                                 233
Product Manager                                                                       212
UI/UX Designer                                                                        165
Data Analyst                                                                          151
Data Engineer / Big Data Engineer                                                     138
Tech Lead / Engineering Lead                                                          134
Recruiter / Recruitment Specialist / Technical Recruiter                              130
SysAdmin                                                                               97
Product Designer                                                                       90
QA Lead                                                                                85
Data Scientist                                                                         72
Customer Support                                                                       65
Technical Support                                                                      61
Product Owner (у продакт менеджменті)                                                  61
HR Manager / HR specialist                                                             56
Delivery Manager                                                                       50
Product Analyst                                                                        48
Head of HR                                                                             46
HR Generalist                                                                          45
Engineering Manager                                                                    44
CTO (Chief Technology Officer) / Technical Director                                    43
ML Engineer (Machine Learning)                                                         43
HR Business Partner                                                                    42
3D Artist                                                                              38
Marketing Manager                                                                      38
2D Artist                                                                              37
Solution Architect                                                                     35
Sales manager / Sales Executive / Sales Operations                                     33
System Analyst                                                                         33
Engineering Lead                                                                       30
SEO Specialist                                                                         29
Game Designer                                                                          29
Content Manager / Content Marketing Manager                                            29
AI Engineer                                                                            29
HR People Partner                                                                      28
Operations Manager                                                                     28
SRE (Site Reliability Engineer)                                                        28
QA Manager / QC Manager                                                                26
Employer Brand Manager                                                                 26
Talent Sourcer / Talent Researcher / Recruitment Researcher                            26
Learning and Development / Training and Development                                    25
Account Manager / Account Executive                                                    23
Head of Recruitment                                                                    23
HR Director (HRD)                                                                      23
Name: count, dtype: int64

In [134]:
counts = df_prepared['position'].value_counts()
rare_positions = counts[counts <= 25].index
df_prepared['position_grouped'] = df_prepared['position'].replace(rare_positions, 'Other')

In [137]:
df_prepared = df_prepared.drop(columns=['position'])
df_prepared

,salary_usd,title,category,english_level,it_experience_years,position_grouped
0,2000.0,Middle,Marketing,Upper-Intermediate,4.00,Marketing Manager
1,3000.0,Senior,Software Engineer,Pre-Intermediate,8.00,"Software Engineer / Developer (frontend, backe..."
2,282.0,Junior,Software Engineer,Pre-Intermediate,0.25,"Software Engineer / Developer (frontend, backe..."
3,2700.0,Middle,Quality Assurance,Upper-Intermediate,4.00,Manual QA
4,2500.0,Middle,Software Engineer,Intermediate,4.00,"Software Engineer / Developer (frontend, backe..."
...,...,...,...,...,...,...
11681,3000.0,Middle,Software Engineer,Intermediate,4.00,"Software Engineer / Developer (frontend, backe..."
11682,2500.0,Middle,Analyst,Upper-Intermediate,1.50,System Analyst
11683,4500.0,Senior,Software Engineer,Upper-Intermediate,9.00,"Software Engineer / Developer (frontend, backe..."
11684,1000.0,Middle,Software Engineer,Upper-Intermediate,3.00,"Software Engineer / Developer (frontend, backe..."
11685,1900.0,Middle,Analyst,Upper-Intermediate,3.00,Business Analyst (BA)

In [139]:
cols = list(df_prepared.columns)
new_cols = cols[:3] + [cols[5]] + cols[3:5] + cols[6:]
df_prepared = df_prepared.reindex(columns=new_cols)
df_prepared

,salary_usd,title,category,position_grouped,english_level,it_experience_years
0,2000.0,Middle,Marketing,Marketing Manager,Upper-Intermediate,4.00
1,3000.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Pre-Intermediate,8.00
2,282.0,Junior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Pre-Intermediate,0.25
3,2700.0,Middle,Quality Assurance,Manual QA,Upper-Intermediate,4.00
4,2500.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Intermediate,4.00
...,...,...,...,...,...,...
11681,3000.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Intermediate,4.00
11682,2500.0,Middle,Analyst,System Analyst,Upper-Intermediate,1.50
11683,4500.0,Senior,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,9.00
11684,1000.0,Middle,Software Engineer,"Software Engineer / Developer (frontend, backe...",Upper-Intermediate,3.00
11685,1900.0,Middle,Analyst,Business Analyst (BA),Upper-Intermediate,3.00

In [ ]:
df_prepared.to_csv('/Users/vladislavpleshko/Documents/VS Code/projects/reg_cycle/data/prepared_data.csv', index=False)